function updateSpeciesICTable(vObj)

set(vObj.h.SpeciesICTable,...
    'ColumnName',{'Species (y)','Data (x)','y=f(x)'},...
    'ColumnEditable',[true true true],...
    'ColumnFormat',{vObj.SpeciesPopupTableItems(:),vObj.PrunedDatasetHeader(:),'char'});