function updateSpeciesDataTable(vObj)

set(vObj.h.SpeciesDataTable,...    
    'ColumnName',{'Data (y)','Species (x)','# Tasks per Species','y=f(x)','ObjectiveFcn'},...
    'ColumnEditable',[true true false true true],...
    'ColumnFormat',{vObj.PrunedDatasetHeader(:),vObj.SpeciesPopupTableItems(:),'float','char',vObj.ObjectiveFunctions(:)});
