function M = CustomLineMarkers(m)

M = {
    '+',...
    'o',...
    '*',...
    '.',...
    'x',...
    'square',...
    'diamond',...
    'v',...
    '^',...
    '>',...
    '<',...
    'pentagram',...
    'hexagram',...
    };

if m/numel(M) > 1    
    M = repmat(M,1,ceil(m/numel(M)));    
end
M = M(1:m);