function updateSpeciesDataTable(vObj)

set(vObj.h.SpeciesDataTable,...    
    'ColumnName',{'Data (y)','Species (x)','# Tasks per Species','y=f(x)'},...
    'ColumnEditable',[true true false true],...
    'ColumnFormat',{vObj.DatasetDataColumn(:),vObj.SpeciesPopupTableItems(:),'float','char'});
