function create(vObj)
% create - Creates all parts of the viewer display
% -------------------------------------------------------------------------
% Abstract: This function creates all parts of the viewer display
%
% Syntax:
%           create(vObj)
%
% Inputs:
%           vObj - QSPViewer.Task vObject
%
% Outputs:
%           none
%
% Examples:
%           none
%
% Notes: none
%

% Copyright 2019 The MathWorks, Inc.
%
% Auth/Revision:
%   MathWorks Consulting
%   $Author: agajjala $
%   $Revision: 294 $  $Date: 2016-09-05 20:37:01 -0400 (Mon, 05 Sep 2016) $
% ---------------------------------------------------------------------

%TODO
% Settings controls
% ListSelector needs optional title, subtitle, border

%% Parameters

LabelWidth = 80;
WidgetHeight = 30;
PadMain = 5; %Main padding
Pad = 5; %Inside padding
HSpace = 5; %Space between controls
VSpace = 8;
VSpaceMain = 12;


%% Invoke super class's create

create@uix.abstract.CardViewPane(vObj);

%% Edit Content

vObj.h.MainVLayout = uix.VBox(...
    'Parent',vObj.h.EditContentsPanel,...
    'Spacing',VSpaceMain);

%% Horizontal Layouts

vObj.h.ProjectHLayout = uix.HBox(...
    'Parent',vObj.h.MainVLayout,...
    'Spacing',HSpace);
vObj.h.ModelHLayout = uix.HBox(...
    'Parent',vObj.h.MainVLayout,...
    'Spacing',HSpace);
vObj.h.VarDosSpecHLayout = uix.HBox(...
    'Parent',vObj.h.MainVLayout,...
    'Spacing',2*HSpace); %Extra spacing
vObj.h.RulReaSetHLayout = uix.HBox(...
    'Parent',vObj.h.MainVLayout,...
    'Spacing',2*HSpace); %Extra spacing

% Sizes
vObj.h.MainVLayout.Heights = [WidgetHeight WidgetHeight -1 -1];


%% Project

vObj.h.ProjectLabel = uicontrol(...
    'Parent',vObj.h.ProjectHLayout,...
    'Style','text',...
    'String','Project',...
    'FontSize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left');

vObj.h.ProjectFileSelector = uix.widget.FileSelector(...
    'Parent',vObj.h.ProjectHLayout,...
    'Value', '', ...
    'Units','pixels',...
    'Pattern', {'*.sbproj', 'SimBiology Project (*.sbproj)'}, ...
    'Title', 'SimBiology Project:', ...
    'HorizontalAlignment', 'left',...
    'InvalidForegroundColor',[1 0 0],...
    'Callback',@(h,e)onProjectSelection(vObj,h,e) );

vObj.h.ProjectHLayout.Widths = [LabelWidth -1];


%% Model

vObj.h.ModelLabel = uicontrol(...
    'Parent',vObj.h.ModelHLayout,...
    'Style','text',...
    'String','Model',...
    'FontSize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left');

vObj.h.ModelPopup = uicontrol(...
    'Parent',vObj.h.ModelHLayout,...
    'Style','popup',...
    'String',{' '},...
    'FontSize',10,...
    'Callback',@(h,e)onModelSelection(vObj,h,e) );

vObj.h.ModelHLayout.Widths = [LabelWidth -1];


%% Variants, Doses, Species

vObj.h.VariantsPanel = uix.Panel(...
    'Parent',vObj.h.VarDosSpecHLayout,...
    'Title', 'Variants to activate',...
    'TitlePosition','centertop',...
    'FontWeight','bold',...
    'FontSize',10,...
    'Padding',PadMain);
vObj.h.VariantsSelector = uix.widget.ListSelectorWithInvalids(...
    'Parent',vObj.h.VariantsPanel,...
    'AllowOrdering',true,...
    'AllowDuplicates',true,...
    'Callback',@(h,e)onListSelection(vObj,h,e,'Variants') );
    
vObj.h.DosesPanel = uix.Panel(...
    'Parent',vObj.h.VarDosSpecHLayout,...
    'TitlePosition','centertop',...
    'Title', 'Doses to include',...
    'FontWeight','bold',...
    'FontSize',10,...
    'Padding',PadMain);
vObj.h.DosesSelector = uix.widget.ListSelectorWithInvalids(...
    'Parent',vObj.h.DosesPanel,...
    'AllowOrdering',true,...
    'AllowDuplicates',true,...
    'Callback',@(h,e)onListSelection(vObj,h,e,'Doses') );
    
vObj.h.SpeciesPanel = uix.Panel(...
    'Parent',vObj.h.VarDosSpecHLayout,...
    'Title', 'Species to include',...
    'TitlePosition','centertop',... 
    'FontWeight','bold',...
    'FontSize',10,...
    'Padding',PadMain);
vObj.h.SpeciesSelector = uix.widget.ListSelectorWithInvalids(...
    'Parent',vObj.h.SpeciesPanel,...
    'AllowOrdering',true,...
    'AllowDuplicates',true,...
    'Callback',@(h,e)onListSelection(vObj,h,e,'Species') );


%% Rules, Reactions, Settings

vObj.h.RulesPanel = uix.Panel(...
    'Parent',vObj.h.RulReaSetHLayout,...
    'Title', 'Rules to deactivate',...
    'TitlePosition','centertop',...    
    'FontWeight','bold',...
    'FontSize',10,...
    'Padding',PadMain);
vObj.h.RulesSelector = uix.widget.ListSelectorWithInvalids(...
    'Parent',vObj.h.RulesPanel,...
    'AllowOrdering',true,...
    'AllowDuplicates',true,...
    'Callback',@(h,e)onListSelection(vObj,h,e,'Rules') );
    
vObj.h.ReactionsPanel = uix.Panel(...
    'Parent',vObj.h.RulReaSetHLayout,...   
    'Title', 'Reactions to deactivate',...
    'TitlePosition','centertop',...    
    'FontWeight','bold',...
    'FontSize',10,...
    'Padding',PadMain);
vObj.h.ReactionsSelector = uix.widget.ListSelectorWithInvalids(...
    'Parent',vObj.h.ReactionsPanel,...
    'AllowOrdering',true,...
    'AllowDuplicates',true,...
    'Callback',@(h,e)onListSelection(vObj,h,e,'Reactions') );

vObj.h.SettingsPanel = uix.Panel(...
    'Parent',vObj.h.RulReaSetHLayout,... 
    'Title', 'Settings',...
    'TitlePosition','centertop',...        
    'FontWeight','bold',...
    'FontSize',10,...
    'Padding',PadMain);
vObj.h.SettingsScrollPanel = uix.ScrollingPanel(...
    'Parent', vObj.h.SettingsPanel);

vObj.h.SettingsVLayout = uix.VBox(...
    'Parent',vObj.h.SettingsScrollPanel,...
    'Padding',Pad,...
    'Spacing',VSpace);


%% Settings

vObj.h.OutputTimesEdit = uix.widget.EditFieldWithLabel(...
    'Parent',vObj.h.SettingsVLayout,...
    'LabelLocation','top',...
    'LabelString','Output Times:',...
    'Callback',@(h,e)onEdit(vObj,h,e,'OutputTimes') );

vObj.h.MaxWallClockEdit = uix.widget.EditFieldWithLabel(...
    'Parent',vObj.h.SettingsVLayout,...
    'LabelLocation','top',...
    'LabelString','Max Wall Clock (sec):',...
    'Callback',@(h,e)onEdit(vObj,h,e,'MaxWallClock') );

vObj.h.RunSteadyStateCheckbox = matlab.ui.control.UIControl( ...
    'Parent',vObj.h.SettingsVLayout,...
    'Style', 'checkbox', ...
    'FontSize',10,...
    'String','Run to Steady State',...
    'Callback',@(h,e)onEdit(vObj,h,e,'RunSteadyState') );

vObj.h.TimeSteadyStateEdit = uix.widget.EditFieldWithLabel(...
    'Parent',vObj.h.SettingsVLayout,...
    'LabelLocation','top',...
    'LabelString','Time to Steady State:',...
    'Callback',@(h,e)onEdit(vObj,h,e,'TimeSteadyState') );

vObj.h.SettingsVLayout.Heights = [50 50 25 50];
vObj.h.SettingsScrollPanel.Heights = 200;

