function create(vObj)
% create - Creates all parts of the viewer display
% -------------------------------------------------------------------------
% Abstract: This function creates all parts of the viewer display
%
% Syntax:
%           create(vObj)
%
% Inputs:
%           vObj - QSPViewer.Simulation vObject
%
% Outputs:
%           none
%
% Examples:
%           none
%
% Notes: none
%

% Copyright 2019 The MathWorks, Inc.
%
% Auth/Revision:
%   MathWorks Consulting
%   $Author: agajjala $
%   $Revision: 310 $  $Date: 2016-09-07 17:44:13 -0400 (Wed, 07 Sep 2016) $
% ---------------------------------------------------------------------

%% Parameters

LabelWidth = 80;
WidgetHeight = 30;


%% Invoke super class's create

create@uix.abstract.CardViewPane(vObj);


%% Edit Content

EditLayout = uix.VBox(...
    'Parent',vObj.h.EditContentsPanel,...
    'Padding',0,...
    'Spacing',12);

ResultsHLayout = uix.HBox(...
    'Parent',EditLayout,...
    'Spacing',5);
vObj.h.ResultsDirLabel = uicontrol(...
    'Parent',ResultsHLayout,...
    'Style','text',...
    'String','Results Path',...
    'FontSize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left');
% Results Path
vObj.h.ResultsDirSelector = uix.widget.FolderSelector(...
    'Parent',ResultsHLayout,...
    'Value', '', ...
    'Title', 'Select the results directory', ...
    'Tag', 'RootDirectory', ... %the field the result goes in Session
    'InvalidForegroundColor',[1 0 0],...
    'HorizontalAlignment', 'left',...
    'Callback',@(h,e)onFolderSelection(vObj,h,e) );
ResultsHLayout.Widths = [LabelWidth -1];

% Dataset
vObj.h.DatasetPopup = uix.widget.PopupFieldWithLabel(...
    'Parent',EditLayout,...
    'String',{'-'},...
    'Value',1,...
    'LabelString','Dataset',...
    'LabelFontSize',10,...
    'LabelFontWeight','bold',...
    'LabelLocation','left',...
    'LabelWidth',LabelWidth+2,...
    'Tag','DatasetPopup',...
    'Callback',@(h,e)onDatasetPopup(vObj,h,e));

% Group Column
vObj.h.GroupNamePopup = ...
    uix.widget.PopupFieldWithLabel(...
    'Parent',EditLayout,...
    'String',{'-'},...
    'LabelString','Group Column',...
    'LabelFontSize',10,...
    'LabelLocation','left',...
    'LabelWidth',LabelWidth+2,...
    'LabelFontWeight','bold',...
    'Callback',@(h,e)onGroupNamePopup(vObj,h,e));
    
% Simulation Items
vObj.h.ItemsTable = uix.widget.MultiPlatformTable(...
    'Parent',EditLayout,...
    'LabelString','Simulation Items',...
    'LabelFontSize',10,...
    'LabelFontWeight','bold',...
    'LabelLocation','top',...
    'UseButtons',[true true false],...
    'ButtonPosition','left',...
    'ButtonCallback',@(h,e)onItemsButtonPressed(vObj,h,e),...
    'CellEditCallback',@(h,e)onItemsTableEdit(vObj,h,e),...
    'CellSelectionCallback',@(h,e)onItemsTableSelect(vObj,h,e));

% Sizes
EditLayout.Heights = [WidgetHeight WidgetHeight WidgetHeight -1];
    

%% Visualization Content

VisualizationLayout = uix.VBox(...
    'Parent',vObj.h.PlotSettingsPanel,...
    'Padding',0,...
    'Spacing',10);

% Species
vObj.h.PlotSpeciesTable = uix.widget.MultiPlatformTable(...
    'Parent',VisualizationLayout,...
    'LabelString','Species',...
    'LabelFontSize',10,...
    'LabelFontWeight','bold',...
    'LabelLocation','top',...
    'UseButtons',false,...
    'CellEditCallback',@(h,e)onSpeciesTablePlot(vObj,h,e));

% Simulation Items
vObj.h.PlotItemsTable = uix.widget.MultiPlatformTable(...
    'Parent',VisualizationLayout,...
    'LabelString','Simulation Items',...
    'LabelFontSize',10,...
    'LabelFontWeight','bold',...
    'LabelLocation','top',...
    'UseButtons',false,...
    'CellSelectionCallback',@(h,e)onItemsTableSelectionPlot(vObj,h,e),...
    'CellEditCallback',@(h,e)onItemsTablePlot(vObj,h,e));

% Data
vObj.h.PlotDatasetTable = uix.widget.MultiPlatformTable(...
    'Parent',VisualizationLayout,...
    'LabelString','Data',...
    'LabelFontSize',10,...
    'LabelFontWeight','bold',...
    'LabelLocation','top',...
    'UseButtons',false,...
    'CellEditCallback',@(h,e)onDataTablePlot(vObj,h,e));

% Group (dataset)
vObj.h.PlotGroupTable = uix.widget.MultiPlatformTable(...
    'Parent',VisualizationLayout,...
    'LabelString','Group (dataset)',...
    'LabelFontSize',10,...
    'LabelFontWeight','bold',...
    'LabelLocation','top',...
    'UseButtons',false,...
    'CellSelectionCallback',@(h,e)onGroupTableSelectionPlot(vObj,h,e),...
    'CellEditCallback',@(h,e)onGroupTablePlot(vObj,h,e));

% Sizes
VisualizationLayout.Heights = [-1 -1 -1 -1];


%% Resize

% Attach a resize function
vObj.h.EditPanel.ResizeFcn = @(h,e)onResize(vObj,h,e);
vObj.h.VisualizePanel.ResizeFcn = @(h,e)onResize(vObj,h,e);

